### PR TITLE
Module Support

### PR DESCRIPTION
**Pull request by jasiqli**
Add `index.mjs` with `export default`. This is useful when using with Deno such as with Netlify Edge Functions.

### CODE REVIEW

**Comment by tylersticka** [comment]
I love the idea of making this a module.

@cloudfour/dev Any thoughts on best practices for keeping this package DRY since 99% of the code is now identical between `index.js` and `index.mjs`? Anything different we should do in `package.json` to expose both the vanilla and module, or is one more easily translatable to the other down the line?

**Comment by gerardo-rodriguez** [comment]
Excellent idea! I'd have to do more research to figure out what is considered a best practice. I did a quick search and found an article that talks about [creating a "hybrid npm module for ESM and CommonJS"](https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html). Perhaps that is a starting point? It's an interesting challenge!

**Comment by gerardo-rodriguez** [comment]
One more article, I haven't read through this in its entirety but it might be useful: https://2ality.com/2019/10/hybrid-npm-packages.html

**Comment by jasiqli** [comment]
In terms of "hybrid" modules, [Itty Router](https://github.com/kwhitley/itty-router/) is one of these I know of *(and small enough to understand easily.)*

It uses a [`prebuild`](https://github.com/kwhitley/itty-router/blob/v2.x/prebuild.js) script to replace the `modules.exports` etc.

**Comment by tylersticka** [comment]
@jasiqli Just merged a different solution (#121)  and published as `1.1.0`. You should now be able to `import` or `require` this module! If you encounter problems be sure to open an issue. Thanks again!

**Pull request closed without merging**
